image: Visual Studio 2017

version: 2.0.1.{build}

branches:
  only:
    - master

skip_commits:
  message: /updated? readme.*s/

environment:
  NUGET_API_KEY:
    secure: vwJBhbWY9NwSAeYw7iU4i3RjqfVkegrXFyFAJB/uFIYtp5pz0Vw5Htiyfa83v+dg
  APPVEYOR_RDP_PASSWORD:
    secure: Ps2KNyw17/1mtAm9/5/miw==

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: false

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: .\Install-Module.ps1
  - ps: |
      $fullpath = $env:PSModulePath -split ":(?!\\)|;|," | Where-Object {$_ -notlike ([System.Environment]::GetFolderPath("UserProfile")+"*") -and $_ -notlike "$pshome*"} | Select-Object -First 1
      Push-Location
      Set-Location -Path $fullpath
      Get-ChildItem -Path . 
      Pop-Location

on_success:
  - ps: |
      Write-Host $env:APPVEYOR_BUILD_ID
      Write-Host $env:APPVEYOR_BUILD_NUMBER
      Write-Host $env:APPVEYOR_BUILD_VERSION
      

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
