image: Visual Studio 2017

version: 1.0.0.{build}

branches:
  only:
    - master

skip_commits:
  message: /updated? readme.*s/

environment:
  nugetapikey:
    secure: vwJBhbWY9NwSAeYw7iU4i3RjqfVkegrXFyFAJB/uFIYtp5pz0Vw5Htiyfa83v+dg

build: false

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

on_success:
  - ps: |
      Write-Host ${APPVEYOR_BUILD_ID}
      Write-Host ${APPVEYOR_BUILD_NUMBER}
      Write-Host ${APPVEYOR_BUILD_VERSION}
#     $buildInfo = Get-BuildInfo
#     $buildInfo.Version